# Generated by Django 4.1 on 2023-01-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
    ]
