# Generated by Django 4.1 on 2023-01-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='group_id',
            field=models.CharField(default='0', max_length=64),
            preserve_default=False,
        ),
    ]
