# Generated by Django 4.1 on 2023-01-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("groups", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devices", models.ManyToManyField(blank=True, to="devices.device")),
                ("groups", models.ManyToManyField(blank=True, to="groups.group")),
                ("rooms", models.ManyToManyField(blank=True, to="rooms.room")),
            ],
        ),
    ]
